# Generated by Django 5.1 on 2024-08-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_razaganado_alter_cabezaganado_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_potrero', models.CharField(max_length=50)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.finca')),
            ],
        ),
    ]
