# Generated by Django 5.1 on 2024-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_potrero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabezaganado',
            name='mastitis',
            field=models.CharField(choices=[('x', 'No Evaluado'), ('y', 'Probable'), ('n', 'No Probable')], default='x', max_length=1),
        ),
    ]
