# Generated by Django 5.1 on 2024-08-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cabezaganado_mastitis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganadofinca',
            name='potrero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.potrero'),
        ),
    ]
