# Generated by Django 5.1 on 2024-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ganadofinca_potrero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganadofinca',
            name='potrero',
            field=models.IntegerField(),
        ),
    ]
